name: 03 Filter Events

on:
  pull_request:
    types:
      - closed
  push:
#    branches-ignore:
#      - master
    paths:
      - "routes/*.php"
jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Step 2
        run: echo "Hello, World! 22 "
