name: 07 Basics Conditions
run-name: ${{ github.actor }} Explaining context data - Try Number ${{ github.run_number }}

on:
  pull_request:
    types:
      - closed

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world if the condition is met
        run : echo "Hello, World!"
