name: 08 Basics Variables
run-name: ${{ github.actor }} Explaining variables - Try Number ${{ github.run_number }}

env:
  MY_NAME: "Mohamed Hathout"

on:
  workflow_dispatch

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
#        run: echo $MY_NAME # %MY_NAME% Access in windows
        run: echo ${{env.MY_NAME}}
