name: 11 Basics Expressions
run-name: ${{ github.actor }} Explaining variables - Try Number ${{ github.run_number }}

env:
  RUN_NUMBER: ${{ github.run_number == 1 && 'Greater than 1' || 'Less than 1' }}
  TESTING_VALUE: ${{contains('Hello World','wor' )}}

on:
  push


jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print run number
#        run: echo ${{env.TESTING_VALUE}}
        run: exit 1
      - name: Print run number 2
        if: ${{failure()}}
        run: echo ${{env.TESTING_VALUE}}
