name: 12 Basics Permissions
run-name: ${{ github.actor }} Explaining variables - Try Number ${{ github.run_number }}

env:
  MY_NAME: "Mohamed Hathout"

on:
  push


jobs:
  open-isseue:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate testing failure
        run: exit 1

      - name: Open New issue
        if: failure()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.github_token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ vars.CREATE_ISSUE_API_ENDPOINT }} \
          -d '{"title":"Testing Failure","body":"This issue opened by gituhub actions "}'
