name: 14 Strategy Matrix
run-name: ${{ github.actor }} Explaining Strategy Matrix - Try Number ${{ github.run_number }}

on:
  push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        php_version: [7.4, 8.0, 8.1]
    steps:
      - name: Build Project
        run: echo "Build Project on os (${{ matrix.os }}) with PHP version (${{ matrix.php_version }})"

