name: 16 Basics Marketplace
on:
  push

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    container:
      image: php:7.2
    steps:
#      - name: Setup Php Version 7.2
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.4'
     - name: Print Hello World
       run: php -v

