name: 18 Basics Services
on:
  push

jobs:
  redis-job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
     - name: Install redis CLI
       run: sudo apt-get install -y redis-tools

     - name: Check Redis Connection
       run: redis-cli -h redis ping


