name: 18 Basics Services
on:
  workflow_dispatch

jobs:
  redis-job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
    steps:
     - name: Check Redis Connection
       run: redis-cli ping

