name: 18 Basics Services alternative
on:
  push

jobs:
  redis-job:
    runs-on: ubuntu-latest
    steps:
     - name: Install redis CLI
       run: sudo apt-get install -y redis-tools

     - name: Check Redis Connection
       run: redis-cli ping


