name: 20 Basics Custom Actions
on:
  push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Echo Hello World
        uses: ./.github/actions/print-hello-world


