name: 22 GitHub CLI - Open New Issue

on:
  push

permissions:
  issues: write

jobs:
  open-new-issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Open New Issue
        run: gh issue create --title "New Issue on github" --body "Nothing works"
