name: Example 01 - Commenting on PR
run-name: Example 01 - Commenting on PR

on:
  pull_request:
    types:
      - closed


jobs:
  open-new-issue-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: sudo apt install gh -y

      - name: Open New Issue
        run: gh pr comment ${{env.PR_NUMBER}} --body "Your PR is closed"



